{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "\npython-django was updated to 1.5.10 fixing bugs and security issues:\n\n    * Prevented reverse() from generating URLs pointing to other hosts to\n      prevent phishing attacks. (bnc#893087, CVE-2014-0480)\n    * Removed O(n) algorithm when uploading duplicate file names to fix\n      file upload denial of service. (bnc#893088, CVE-2014-0481)\n    * Modified RemoteUserMiddleware to logout on REMOTE_USE change to\n      prevent session hijacking. (bnc#893089, CVE-2014-0482)\n    * Prevented data leakage in contrib.admin via query string\n      manipulation. (bnc#893090, CVE-2014-0483)\n\nSecurity Issues:\n\n    * CVE-2014-0480\n      <http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0480>\n    * CVE-2014-0481\n      <http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0481>\n    * CVE-2014-0482\n      <http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0482>\n    * CVE-2014-0483\n      <http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-0483>\n\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "sleclo40sp3-python-django",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2015:0563-1",
				"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20150563-1/"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2015_0563-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2015:0563-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-March/001310.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 893087",
				"url": "https://bugzilla.suse.com/893087"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 893088",
				"url": "https://bugzilla.suse.com/893088"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 893089",
				"url": "https://bugzilla.suse.com/893089"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 893090",
				"url": "https://bugzilla.suse.com/893090"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 913053",
				"url": "https://bugzilla.suse.com/913053"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 913054",
				"url": "https://bugzilla.suse.com/913054"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 913055",
				"url": "https://bugzilla.suse.com/913055"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 913056",
				"url": "https://bugzilla.suse.com/913056"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 914706",
				"url": "https://bugzilla.suse.com/914706"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 923176",
				"url": "https://bugzilla.suse.com/923176"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-0480 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-0480/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-0481 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-0481/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-0482 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-0482/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-0483 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-0483/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-0219 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-0219/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-0220 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-0220/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-0221 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-0221/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-0222 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-0222/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-2316 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-2316/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2015-2317 page",
				"url": "https://www.suse.com/security/cve/CVE-2015-2317/"
			}
		],
		"title": "Security update for python-django",
		"tracking": {
			"current_release_date": "2014-09-03T15:51:02Z",
			"generator": {
				"date": "2014-09-03T15:51:02Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2015:0563-1",
			"initial_release_date": "2014-09-03T15:51:02Z",
			"revision_history": [
				{
					"date": "2014-09-03T15:51:02Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-django-1.5.10-0.11.1.x86_64",
								"product": {
									"name": "python-django-1.5.10-0.11.1.x86_64",
									"product_id": "python-django-1.5.10-0.11.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 4",
								"product": {
									"name": "SUSE OpenStack Cloud 4",
									"product_id": "SUSE OpenStack Cloud 4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:cloud:4"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-django-1.5.10-0.11.1.x86_64 as component of SUSE OpenStack Cloud 4",
					"product_id": "SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				},
				"product_reference": "python-django-1.5.10-0.11.1.x86_64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 4"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2014-0480",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-0480"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The core.urlresolvers.reverse function in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not properly validate URLs, which allows remote attackers to conduct phishing attacks via a // (slash slash) in a URL, which triggers a scheme-relative URL to be generated.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-0480",
					"url": "https://www.suse.com/security/cve/CVE-2014-0480"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 893087 for CVE-2014-0480",
					"url": "https://bugzilla.suse.com/893087"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2014-0480",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-0480"
		},
		{
			"cve": "CVE-2014-0481",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-0481"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The default configuration for the file upload handling system in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 uses a sequential file name generation process when a file with a conflicting name is uploaded, which allows remote attackers to cause a denial of service (CPU consumption) by unloading a multiple files with the same name.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-0481",
					"url": "https://www.suse.com/security/cve/CVE-2014-0481"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 893088 for CVE-2014-0481",
					"url": "https://bugzilla.suse.com/893088"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2014-0481",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-0481"
		},
		{
			"cve": "CVE-2014-0482",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-0482"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The contrib.auth.middleware.RemoteUserMiddleware middleware in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3, when using the contrib.auth.backends.RemoteUserBackend backend, allows remote authenticated users to hijack web sessions via vectors related to the REMOTE_USER header.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-0482",
					"url": "https://www.suse.com/security/cve/CVE-2014-0482"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 893089 for CVE-2014-0482",
					"url": "https://bugzilla.suse.com/893089"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2014-0482",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-0482"
		},
		{
			"cve": "CVE-2014-0483",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-0483"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The administrative interface (contrib.admin) in Django before 1.4.14, 1.5.x before 1.5.9, 1.6.x before 1.6.6, and 1.7 before release candidate 3 does not check if a field represents a relationship between models, which allows remote authenticated users to obtain sensitive information via a to_field parameter in a popup action to an admin change form page, as demonstrated by a /admin/auth/user/?pop=1&t=password URI.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-0483",
					"url": "https://www.suse.com/security/cve/CVE-2014-0483"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 893090 for CVE-2014-0483",
					"url": "https://bugzilla.suse.com/893090"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2014-0483",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "low"
				}
			],
			"title": "CVE-2014-0483"
		},
		{
			"cve": "CVE-2015-0219",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-0219"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 allows remote attackers to spoof WSGI headers by using an _ (underscore) character instead of a - (dash) character in an HTTP header, as demonstrated by an X-Auth_User header.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-0219",
					"url": "https://www.suse.com/security/cve/CVE-2015-0219"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 913053 for CVE-2015-0219",
					"url": "https://bugzilla.suse.com/913053"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2015-0219",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-0219"
		},
		{
			"cve": "CVE-2015-0220",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-0220"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The django.util.http.is_safe_url function in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 does not properly handle leading whitespaces, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a crafted URL, related to redirect URLs, as demonstrated by a \"\\njavascript:\" URL.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-0220",
					"url": "https://www.suse.com/security/cve/CVE-2015-0220"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 913054 for CVE-2015-0220",
					"url": "https://bugzilla.suse.com/913054"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2015-0220",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-0220"
		},
		{
			"cve": "CVE-2015-0221",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-0221"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The django.views.static.serve view in Django before 1.4.18, 1.6.x before 1.6.10, and 1.7.x before 1.7.3 reads files an entire line at a time, which allows remote attackers to cause a denial of service (memory consumption) via a long line in a file.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-0221",
					"url": "https://www.suse.com/security/cve/CVE-2015-0221"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 913056 for CVE-2015-0221",
					"url": "https://bugzilla.suse.com/913056"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2015-0221",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-0221"
		},
		{
			"cve": "CVE-2015-0222",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-0222"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "ModelMultipleChoiceField in Django 1.6.x before 1.6.10 and 1.7.x before 1.7.3, when show_hidden_initial is set to True, allows remote attackers to cause a denial of service by submitting duplicate values, which triggers a large number of SQL queries.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-0222",
					"url": "https://www.suse.com/security/cve/CVE-2015-0222"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 913055 for CVE-2015-0222",
					"url": "https://bugzilla.suse.com/913055"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 919763 for CVE-2015-0222",
					"url": "https://bugzilla.suse.com/919763"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-0222"
		},
		{
			"cve": "CVE-2015-2316",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-2316"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The utils.html.strip_tags function in Django 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1, when using certain versions of Python, allows remote attackers to cause a denial of service (infinite loop) by increasing the length of the input string.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-2316",
					"url": "https://www.suse.com/security/cve/CVE-2015-2316"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 923172 for CVE-2015-2316",
					"url": "https://bugzilla.suse.com/923172"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-2316"
		},
		{
			"cve": "CVE-2015-2317",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2015-2317"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "The utils.http.is_safe_url function in Django before 1.4.20, 1.5.x, 1.6.x before 1.6.11, 1.7.x before 1.7.7, and 1.8.x before 1.8c1 does not properly validate URLs, which allows remote attackers to conduct cross-site scripting (XSS) attacks via a control character in a URL, as demonstrated by a \\x08javascript: URL.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2015-2317",
					"url": "https://www.suse.com/security/cve/CVE-2015-2317"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 923176 for CVE-2015-2317",
					"url": "https://bugzilla.suse.com/923176"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-django-1.5.10-0.11.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2014-09-03T15:51:02Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2015-2317"
		}
	]
}
