{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-PyYAML",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "\npython-PyYAML was updated to fix one security issue which could have \nallowed an attacker to cause a denial of service by supplying specially \ncrafted strings. (CVE-2014-9130, bsc#921588)\n\nSecurity Issues:\n\n    * CVE-2014-9130\n      <http://cve.mitre.org/cgi-bin/cvename.cgi?name=CVE-2014-9130>\n\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "sleclo40sp3-python-PyYAML,sleclo50sp3-python-PyYAML",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2015_0699-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2015:0699-1",
				"url": "https://www.suse.com/support/update/announcement/2015/suse-su-20150699-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2015:0699-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2015-April/001341.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 921588",
				"url": "https://bugzilla.suse.com/921588"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2014-9130 page",
				"url": "https://www.suse.com/security/cve/CVE-2014-9130/"
			}
		],
		"title": "Security update for python-PyYAML",
		"tracking": {
			"current_release_date": "2015-03-12T09:33:36Z",
			"generator": {
				"date": "2015-03-12T09:33:36Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2015:0699-1",
			"initial_release_date": "2015-03-12T09:33:36Z",
			"revision_history": [
				{
					"date": "2015-03-12T09:33:36Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-PyYAML-3.10-0.15.1.x86_64",
								"product": {
									"name": "python-PyYAML-3.10-0.15.1.x86_64",
									"product_id": "python-PyYAML-3.10-0.15.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python-PyYAML-3.10-0.13.1.x86_64",
								"product": {
									"name": "python-PyYAML-3.10-0.13.1.x86_64",
									"product_id": "python-PyYAML-3.10-0.13.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 4",
								"product": {
									"name": "SUSE OpenStack Cloud 4",
									"product_id": "SUSE OpenStack Cloud 4",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:cloud:4"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 5",
								"product": {
									"name": "SUSE OpenStack Cloud 5",
									"product_id": "SUSE OpenStack Cloud 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:cloud:5"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-PyYAML-3.10-0.15.1.x86_64 as component of SUSE OpenStack Cloud 4",
					"product_id": "SUSE OpenStack Cloud 4:python-PyYAML-3.10-0.15.1.x86_64"
				},
				"product_reference": "python-PyYAML-3.10-0.15.1.x86_64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 4"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-PyYAML-3.10-0.13.1.x86_64 as component of SUSE OpenStack Cloud 5",
					"product_id": "SUSE OpenStack Cloud 5:python-PyYAML-3.10-0.13.1.x86_64"
				},
				"product_reference": "python-PyYAML-3.10-0.13.1.x86_64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 5"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2014-9130",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2014-9130"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "scanner.c in LibYAML 0.1.5 and 0.1.6, as used in the YAML-LibYAML (aka YAML-XS) module for Perl, allows context-dependent attackers to cause a denial of service (assertion failure and crash) via vectors involving line-wrapping.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 4:python-PyYAML-3.10-0.15.1.x86_64",
					"SUSE OpenStack Cloud 5:python-PyYAML-3.10-0.13.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2014-9130",
					"url": "https://www.suse.com/security/cve/CVE-2014-9130"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 907809 for CVE-2014-9130",
					"url": "https://bugzilla.suse.com/907809"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 911782 for CVE-2014-9130",
					"url": "https://bugzilla.suse.com/911782"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 921588 for CVE-2014-9130",
					"url": "https://bugzilla.suse.com/921588"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 4:python-PyYAML-3.10-0.15.1.x86_64",
						"SUSE OpenStack Cloud 5:python-PyYAML-3.10-0.13.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2015-03-12T09:33:36Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2014-9130"
		}
	]
}
