{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\n- Fixed potential XSS in admin ForeignKeyRawIdWidget (bsc#1172166, CVE-2020-13596)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2020-2055,SUSE-Storage-5-2020-2055",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2020_2055-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2020:2055-1",
				"url": "https://www.suse.com/support/update/announcement/2020/suse-su-20202055-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2020:2055-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2020-July/007187.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1172166",
				"url": "https://bugzilla.suse.com/1172166"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2020-13596 page",
				"url": "https://www.suse.com/security/cve/CVE-2020-13596/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2020-07-27T14:07:25Z",
			"generator": {
				"date": "2020-07-27T14:07:25Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2020:2055-1",
			"initial_release_date": "2020-07-27T14:07:25Z",
			"revision_history": [
				{
					"date": "2020-07-27T14:07:25Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.6.11-6.13.1.noarch",
								"product": {
									"name": "python-Django-1.6.11-6.13.1.noarch",
									"product_id": "python-Django-1.6.11-6.13.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Enterprise Storage 5",
								"product": {
									"name": "SUSE Enterprise Storage 5",
									"product_id": "SUSE Enterprise Storage 5",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:ses:5"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.6.11-6.13.1.noarch as component of SUSE Enterprise Storage 5",
					"product_id": "SUSE Enterprise Storage 5:python-Django-1.6.11-6.13.1.noarch"
				},
				"product_reference": "python-Django-1.6.11-6.13.1.noarch",
				"relates_to_product_reference": "SUSE Enterprise Storage 5"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2020-13596",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-13596"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7. Query parameters generated by the Django admin ForeignKeyRawIdWidget were not properly URL encoded, leading to a possibility of an XSS attack.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE Enterprise Storage 5:python-Django-1.6.11-6.13.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-13596",
					"url": "https://www.suse.com/security/cve/CVE-2020-13596"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1172166 for CVE-2020-13596",
					"url": "https://bugzilla.suse.com/1172166"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1172167 for CVE-2020-13596",
					"url": "https://bugzilla.suse.com/1172167"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.13.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.4,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:L/UI:N/S:C/C:L/I:L/A:N",
						"version": "3.1"
					},
					"products": [
						"SUSE Enterprise Storage 5:python-Django-1.6.11-6.13.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2020-07-27T14:07:25Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2020-13596"
		}
	]
}
