{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\n- CVE-2019-14232: Fixed a denial of service in 'django.utils.text.Truncator' (bsc#1142880).\n- CVE-2019-14233: Fixed a denial of service in strip_tags() (bsc#1142882).\n- CVE-2019-14234: Fixed an SQL injection in key and index lookups for 'JSONField'/'HStoreField' (bsc#1142883).\n- CVE-2019-14235: Fixed a potential memory exhaustion in 'django.utils.encoding.uri_to_iri()' (bsc#1142885).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2019-2180,SUSE-OpenStack-Cloud-7-2019-2180",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2019_2180-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2019:2180-1",
				"url": "https://www.suse.com/support/update/announcement/2019/suse-su-20192180-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2019:2180-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2019-August/005830.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142880",
				"url": "https://bugzilla.suse.com/1142880"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142882",
				"url": "https://bugzilla.suse.com/1142882"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142883",
				"url": "https://bugzilla.suse.com/1142883"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1142885",
				"url": "https://bugzilla.suse.com/1142885"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14232 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14232/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14233 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14233/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14234 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14234/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-14235 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-14235/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2019-08-19T14:48:36Z",
			"generator": {
				"date": "2019-08-19T14:48:36Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2019:2180-1",
			"initial_release_date": "2019-08-19T14:48:36Z",
			"revision_history": [
				{
					"date": "2019-08-19T14:48:36Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.8.19-3.15.1.noarch",
								"product": {
									"name": "python-Django-1.8.19-3.15.1.noarch",
									"product_id": "python-Django-1.8.19-3.15.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 7",
								"product": {
									"name": "SUSE OpenStack Cloud 7",
									"product_id": "SUSE OpenStack Cloud 7",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.8.19-3.15.1.noarch as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
				},
				"product_reference": "python-Django-1.8.19-3.15.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-14232",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14232"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If django.utils.text.Truncator's chars() and words() methods were passed the html=True argument, they were extremely slow to evaluate certain inputs due to a catastrophic backtracking vulnerability in a regular expression. The chars() and words() methods are used to implement the truncatechars_html and truncatewords_html template filters, which were thus vulnerable.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14232",
					"url": "https://www.suse.com/security/cve/CVE-2019-14232"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142880 for CVE-2019-14232",
					"url": "https://bugzilla.suse.com/1142880"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1215978 for CVE-2019-14232",
					"url": "https://bugzilla.suse.com/1215978"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1220358 for CVE-2019-14232",
					"url": "https://bugzilla.suse.com/1220358"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-19T14:48:36Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-14232"
		},
		{
			"cve": "CVE-2019-14233",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14233"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to the behaviour of the underlying HTMLParser, django.utils.html.strip_tags would be extremely slow to evaluate certain inputs containing large sequences of nested incomplete HTML entities.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14233",
					"url": "https://www.suse.com/security/cve/CVE-2019-14233"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142882 for CVE-2019-14233",
					"url": "https://bugzilla.suse.com/1142882"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-19T14:48:36Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-14233"
		},
		{
			"cve": "CVE-2019-14234",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14234"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. Due to an error in shallow key transformation, key and index lookups for django.contrib.postgres.fields.JSONField, and key lookups for django.contrib.postgres.fields.HStoreField, were subject to SQL injection. This could, for example, be exploited via crafted use of \"OR 1=1\" in a key or index name to return all records, using a suitably crafted dictionary, with dictionary expansion, as the **kwargs passed to the QuerySet.filter() function.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14234",
					"url": "https://www.suse.com/security/cve/CVE-2019-14234"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142883 for CVE-2019-14234",
					"url": "https://bugzilla.suse.com/1142883"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.0"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-19T14:48:36Z",
					"details": "important"
				}
			],
			"title": "CVE-2019-14234"
		},
		{
			"cve": "CVE-2019-14235",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-14235"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Django 1.11.x before 1.11.23, 2.1.x before 2.1.11, and 2.2.x before 2.2.4. If passed certain inputs, django.utils.encoding.uri_to_iri could lead to significant memory usage due to a recursion when repercent-encoding invalid UTF-8 octet sequences.",
					"title": "CVE description"
				}
			],
			"product_status": {},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-14235",
					"url": "https://www.suse.com/security/cve/CVE-2019-14235"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1142885 for CVE-2019-14235",
					"url": "https://bugzilla.suse.com/1142885"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:L",
						"version": "3.0"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.15.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-08-19T14:48:36Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2019-14235"
		}
	]
}
