{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n\nSecurity issue fixed:\n\n- CVE-2019-3498: Fixed a content spoofing attack in the default 404 page (bsc#1120932)\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2019-483,SUSE-OpenStack-Cloud-7-2019-483",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2019:0483-1",
				"url": "https://www.suse.com/support/update/announcement/2019/suse-su-20190483-1/"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2019_0483-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2019:0483-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2019-February/005149.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1120932",
				"url": "https://bugzilla.suse.com/1120932"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2019-3498 page",
				"url": "https://www.suse.com/security/cve/CVE-2019-3498/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2019-02-25T10:59:40Z",
			"generator": {
				"date": "2019-02-25T10:59:40Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2019:0483-1",
			"initial_release_date": "2019-02-25T10:59:40Z",
			"revision_history": [
				{
					"date": "2019-02-25T10:59:40Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.8.19-3.9.1.noarch",
								"product": {
									"name": "python-Django-1.8.19-3.9.1.noarch",
									"product_id": "python-Django-1.8.19-3.9.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 7",
								"product": {
									"name": "SUSE OpenStack Cloud 7",
									"product_id": "SUSE OpenStack Cloud 7",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.8.19-3.9.1.noarch as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-Django-1.8.19-3.9.1.noarch"
				},
				"product_reference": "python-Django-1.8.19-3.9.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2019-3498",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2019-3498"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Django 1.11.x before 1.11.18, 2.0.x before 2.0.10, and 2.1.x before 2.1.5, an Improper Neutralization of Special Elements in Output Used by a Downstream Component issue exists in django.views.defaults.page_not_found(), leading to content spoofing (in a 404 error page) if a user fails to recognize that a crafted URL has malicious content.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.9.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2019-3498",
					"url": "https://www.suse.com/security/cve/CVE-2019-3498"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1120932 for CVE-2019-3498",
					"url": "https://bugzilla.suse.com/1120932"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1139945 for CVE-2019-3498",
					"url": "https://bugzilla.suse.com/1139945"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.9.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 4.3,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:N/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Django-1.8.19-3.9.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2019-02-25T10:59:40Z",
					"details": "low"
				}
			],
			"title": "CVE-2019-3498"
		}
	]
}
