{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django1",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django1 fixes the following issues:\n\n- CVE-2023-24580: Fixed potential DoS in file uploads (bsc#1208082).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2023-2080,SUSE-OpenStack-Cloud-9-2023-2080,SUSE-OpenStack-Cloud-Crowbar-9-2023-2080",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2023_2080-1.json"
			},
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2023:2080-1",
				"url": "https://www.suse.com/support/update/announcement/2023/suse-su-20232080-1/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2023:2080-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2023-May/014776.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1208082",
				"url": "https://bugzilla.suse.com/1208082"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2023-24580 page",
				"url": "https://www.suse.com/security/cve/CVE-2023-24580/"
			}
		],
		"title": "Security update for python-Django1",
		"tracking": {
			"current_release_date": "2023-05-02T10:56:19Z",
			"generator": {
				"date": "2023-05-02T10:56:19Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2023:2080-1",
			"initial_release_date": "2023-05-02T10:56:19Z",
			"revision_history": [
				{
					"date": "2023-05-02T10:56:19Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django1-1.11.29-3.44.1.noarch",
								"product": {
									"name": "python-Django1-1.11.29-3.44.1.noarch",
									"product_id": "python-Django1-1.11.29-3.44.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-Django1-1.11.29-3.44.1.noarch",
								"product": {
									"name": "python3-Django1-1.11.29-3.44.1.noarch",
									"product_id": "python3-Django1-1.11.29-3.44.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 9",
								"product": {
									"name": "SUSE OpenStack Cloud 9",
									"product_id": "SUSE OpenStack Cloud 9",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:9"
									}
								}
							},
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud Crowbar 9",
								"product": {
									"name": "SUSE OpenStack Cloud Crowbar 9",
									"product_id": "SUSE OpenStack Cloud Crowbar 9",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud-crowbar:9"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django1-1.11.29-3.44.1.noarch as component of SUSE OpenStack Cloud 9",
					"product_id": "SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.44.1.noarch"
				},
				"product_reference": "python-Django1-1.11.29-3.44.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud 9"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django1-1.11.29-3.44.1.noarch as component of SUSE OpenStack Cloud Crowbar 9",
					"product_id": "SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.44.1.noarch"
				},
				"product_reference": "python-Django1-1.11.29-3.44.1.noarch",
				"relates_to_product_reference": "SUSE OpenStack Cloud Crowbar 9"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2023-24580",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2023-24580"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in the Multipart Request Parser in Django 3.2 before 3.2.18, 4.0 before 4.0.10, and 4.1 before 4.1.7. Passing certain inputs (e.g., an excessive number of parts) to multipart forms could result in too many open files or memory exhaustion, and provided a potential vector for a denial-of-service attack.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.44.1.noarch",
					"SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.44.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2023-24580",
					"url": "https://www.suse.com/security/cve/CVE-2023-24580"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1208082 for CVE-2023-24580",
					"url": "https://bugzilla.suse.com/1208082"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.44.1.noarch",
						"SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.44.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 9:python-Django1-1.11.29-3.44.1.noarch",
						"SUSE OpenStack Cloud Crowbar 9:python-Django1-1.11.29-3.44.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2023-05-02T10:56:19Z",
					"details": "important"
				}
			],
			"title": "CVE-2023-24580"
		}
	]
}
