{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "important"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2023 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Pillow",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Pillow fixes the following issues:\n\n- CVE-2021-25290: Fixed a negative-offset memcpy with an invalid size in TiffDecode.c (bsc#1183105).\n- CVE-2021-27922,CVE-2021-27923: Fixed improper reported size of a contained image (bsc#1183108,bsc#1183107)  \n- CVE-2020-35653: Fixed buffer over-read in PcxDecode when decoding a crafted PCX file (bsc#1180834).\n- CVE-2021-25287: Fixed out-of-bounds read in J2kDecode in j2ku_graya_la (bsc#1185805).\n- CVE-2021-25288: Fixed out-of-bounds read in J2kDecode in j2ku_gray_i (bsc#1185803).\n- CVE-2021-28675: Fixed DoS in PsdImagePlugin (bsc#1185804).\n- CVE-2021-28677: Fixed DoS in the open phase via a malicious EPS file (bsc#1185785).\n- CVE-2021-28676: Fixed infinite loop in FliDecode.c (bsc#1185786).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "SUSE-2021-1940,SUSE-OpenStack-Cloud-7-2021-1940",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "self",
				"summary": "URL for SUSE-SU-2021:1940-1",
				"url": "https://www.suse.com/support/update/announcement/2021/suse-su-20211940-1/"
			},
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/suse-su-2021_1940-1.json"
			},
			{
				"category": "self",
				"summary": "E-Mail link for SUSE-SU-2021:1940-1",
				"url": "https://lists.suse.com/pipermail/sle-security-updates/2021-June/008989.html"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1180834",
				"url": "https://bugzilla.suse.com/1180834"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1183105",
				"url": "https://bugzilla.suse.com/1183105"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1183107",
				"url": "https://bugzilla.suse.com/1183107"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1183108",
				"url": "https://bugzilla.suse.com/1183108"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1185785",
				"url": "https://bugzilla.suse.com/1185785"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1185786",
				"url": "https://bugzilla.suse.com/1185786"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1185803",
				"url": "https://bugzilla.suse.com/1185803"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1185804",
				"url": "https://bugzilla.suse.com/1185804"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1185805",
				"url": "https://bugzilla.suse.com/1185805"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2020-35653 page",
				"url": "https://www.suse.com/security/cve/CVE-2020-35653/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-25287 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-25287/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-25288 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-25288/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-25290 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-25290/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-27922 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-27922/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-27923 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-27923/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-28675 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-28675/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-28676 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-28676/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2021-28677 page",
				"url": "https://www.suse.com/security/cve/CVE-2021-28677/"
			}
		],
		"title": "Security update for python-Pillow",
		"tracking": {
			"current_release_date": "2021-06-10T08:49:31Z",
			"generator": {
				"date": "2021-06-10T08:49:31Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "SUSE-SU-2021:1940-1",
			"initial_release_date": "2021-06-10T08:49:31Z",
			"revision_history": [
				{
					"date": "2021-06-10T08:49:31Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Pillow-2.8.1-4.22.1.aarch64",
								"product": {
									"name": "python-Pillow-2.8.1-4.22.1.aarch64",
									"product_id": "python-Pillow-2.8.1-4.22.1.aarch64"
								}
							},
							{
								"category": "product_version",
								"name": "python-Pillow-tk-2.8.1-4.22.1.aarch64",
								"product": {
									"name": "python-Pillow-tk-2.8.1-4.22.1.aarch64",
									"product_id": "python-Pillow-tk-2.8.1-4.22.1.aarch64"
								}
							}
						],
						"category": "architecture",
						"name": "aarch64"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Pillow-2.8.1-4.22.1.ppc64le",
								"product": {
									"name": "python-Pillow-2.8.1-4.22.1.ppc64le",
									"product_id": "python-Pillow-2.8.1-4.22.1.ppc64le"
								}
							},
							{
								"category": "product_version",
								"name": "python-Pillow-tk-2.8.1-4.22.1.ppc64le",
								"product": {
									"name": "python-Pillow-tk-2.8.1-4.22.1.ppc64le",
									"product_id": "python-Pillow-tk-2.8.1-4.22.1.ppc64le"
								}
							}
						],
						"category": "architecture",
						"name": "ppc64le"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Pillow-2.8.1-4.22.1.s390x",
								"product": {
									"name": "python-Pillow-2.8.1-4.22.1.s390x",
									"product_id": "python-Pillow-2.8.1-4.22.1.s390x"
								}
							},
							{
								"category": "product_version",
								"name": "python-Pillow-tk-2.8.1-4.22.1.s390x",
								"product": {
									"name": "python-Pillow-tk-2.8.1-4.22.1.s390x",
									"product_id": "python-Pillow-tk-2.8.1-4.22.1.s390x"
								}
							}
						],
						"category": "architecture",
						"name": "s390x"
					},
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Pillow-2.8.1-4.22.1.x86_64",
								"product": {
									"name": "python-Pillow-2.8.1-4.22.1.x86_64",
									"product_id": "python-Pillow-2.8.1-4.22.1.x86_64"
								}
							},
							{
								"category": "product_version",
								"name": "python-Pillow-tk-2.8.1-4.22.1.x86_64",
								"product": {
									"name": "python-Pillow-tk-2.8.1-4.22.1.x86_64",
									"product_id": "python-Pillow-tk-2.8.1-4.22.1.x86_64"
								}
							}
						],
						"category": "architecture",
						"name": "x86_64"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE OpenStack Cloud 7",
								"product": {
									"name": "SUSE OpenStack Cloud 7",
									"product_id": "SUSE OpenStack Cloud 7",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:suse-openstack-cloud:7"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Pillow-2.8.1-4.22.1.aarch64 as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64"
				},
				"product_reference": "python-Pillow-2.8.1-4.22.1.aarch64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Pillow-2.8.1-4.22.1.s390x as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x"
				},
				"product_reference": "python-Pillow-2.8.1-4.22.1.s390x",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Pillow-2.8.1-4.22.1.x86_64 as component of SUSE OpenStack Cloud 7",
					"product_id": "SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				},
				"product_reference": "python-Pillow-2.8.1-4.22.1.x86_64",
				"relates_to_product_reference": "SUSE OpenStack Cloud 7"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2020-35653",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-35653"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Pillow before 8.1.0, PcxDecode has a buffer over-read when decoding a crafted PCX file because the user-supplied stride value is trusted for buffer calculations.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-35653",
					"url": "https://www.suse.com/security/cve/CVE-2020-35653"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1180834 for CVE-2020-35653",
					"url": "https://bugzilla.suse.com/1180834"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 8.1,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2020-35653"
		},
		{
			"cve": "CVE-2021-25287",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-25287"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_graya_la.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-25287",
					"url": "https://www.suse.com/security/cve/CVE-2021-25287"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185805 for CVE-2021-25287",
					"url": "https://bugzilla.suse.com/1185805"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 9.1,
						"baseSeverity": "CRITICAL",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "critical"
				}
			],
			"title": "CVE-2021-25287"
		},
		{
			"cve": "CVE-2021-25288",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-25288"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Pillow before 8.2.0. There is an out-of-bounds read in J2kDecode, in j2ku_gray_i.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-25288",
					"url": "https://www.suse.com/security/cve/CVE-2021-25288"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185803 for CVE-2021-25288",
					"url": "https://bugzilla.suse.com/1185803"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-25288"
		},
		{
			"cve": "CVE-2021-25290",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-25290"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Pillow before 8.1.1. In TiffDecode.c, there is a negative-offset memcpy with an invalid size.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-25290",
					"url": "https://www.suse.com/security/cve/CVE-2021-25290"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1183105 for CVE-2021-25290",
					"url": "https://bugzilla.suse.com/1183105"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-25290"
		},
		{
			"cve": "CVE-2021-27922",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-27922"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Pillow before 8.1.1 allows attackers to cause a denial of service (memory consumption) because the reported size of a contained image is not properly checked for an ICNS container, and thus an attempted memory allocation can be very large.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-27922",
					"url": "https://www.suse.com/security/cve/CVE-2021-27922"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1183108 for CVE-2021-27922",
					"url": "https://bugzilla.suse.com/1183108"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-27922"
		},
		{
			"cve": "CVE-2021-27923",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-27923"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Pillow before 8.1.1 allows attackers to cause a denial of service (memory consumption) because the reported size of a contained image is not properly checked for an ICO container, and thus an attempted memory allocation can be very large.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-27923",
					"url": "https://www.suse.com/security/cve/CVE-2021-27923"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1183107 for CVE-2021-27923",
					"url": "https://bugzilla.suse.com/1183107"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-27923"
		},
		{
			"cve": "CVE-2021-28675",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-28675"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Pillow before 8.2.0. PSDImagePlugin.PsdImageFile lacked a sanity check on the number of input layers relative to the size of the data block. This could lead to a DoS on Image.open prior to Image.load.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-28675",
					"url": "https://www.suse.com/security/cve/CVE-2021-28675"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185804 for CVE-2021-28675",
					"url": "https://bugzilla.suse.com/1185804"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-28675"
		},
		{
			"cve": "CVE-2021-28676",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-28676"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Pillow before 8.2.0. For FLI data, FliDecode did not properly check that the block advance was non-zero, potentially leading to an infinite loop on load.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-28676",
					"url": "https://www.suse.com/security/cve/CVE-2021-28676"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185786 for CVE-2021-28676",
					"url": "https://bugzilla.suse.com/1185786"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-28676"
		},
		{
			"cve": "CVE-2021-28677",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2021-28677"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "An issue was discovered in Pillow before 8.2.0. For EPS data, the readline implementation used in EPSImageFile has to deal with any combination of \\r and \\n as line endings. It used an accidentally quadratic method of accumulating lines while looking for a line ending. A malicious EPS file could use this to perform a DoS of Pillow in the open phase, before an image was accepted for opening.",
					"title": "Vulnerability description"
				}
			],
			"product_status": {
				"fixed": [
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
					"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2021-28677",
					"url": "https://www.suse.com/security/cve/CVE-2021-28677"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1185785 for CVE-2021-28677",
					"url": "https://bugzilla.suse.com/1185785"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.aarch64",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.s390x",
						"SUSE OpenStack Cloud 7:python-Pillow-2.8.1-4.22.1.x86_64"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-06-10T08:49:31Z",
					"details": "important"
				}
			],
			"title": "CVE-2021-28677"
		}
	]
}
