{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-py",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-py fixes the following issues:\n\n- CVE-2020-29651: Fixed regular expression denial of service in svnwc.py (bsc#1179805, bsc#1184505).\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-SLE-15.3-2021-1859",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2021_1859-1.json"
			},
			{
				"category": "self",
				"summary": "URL for openSUSE-SU-2021:1859-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/B5MZ7NDWQ2PACIOK5L2D7CNODUCJCARI/"
			},
			{
				"category": "self",
				"summary": "E-Mail link for openSUSE-SU-2021:1859-1",
				"url": "https://lists.opensuse.org/archives/list/security-announce@lists.opensuse.org/thread/B5MZ7NDWQ2PACIOK5L2D7CNODUCJCARI/"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1179805",
				"url": "https://bugzilla.suse.com/1179805"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1184505",
				"url": "https://bugzilla.suse.com/1184505"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2020-29651 page",
				"url": "https://www.suse.com/security/cve/CVE-2020-29651/"
			}
		],
		"title": "Security update for python-py",
		"tracking": {
			"current_release_date": "2021-07-11T09:21:16Z",
			"generator": {
				"date": "2021-07-11T09:21:16Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2021:1859-1",
			"initial_release_date": "2021-07-11T09:21:16Z",
			"revision_history": [
				{
					"date": "2021-07-11T09:21:16Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python2-py-1.8.1-5.6.1.noarch",
								"product": {
									"name": "python2-py-1.8.1-5.6.1.noarch",
									"product_id": "python2-py-1.8.1-5.6.1.noarch"
								}
							},
							{
								"category": "product_version",
								"name": "python3-py-1.8.1-5.6.1.noarch",
								"product": {
									"name": "python3-py-1.8.1-5.6.1.noarch",
									"product_id": "python3-py-1.8.1-5.6.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "openSUSE Leap 15.3",
								"product": {
									"name": "openSUSE Leap 15.3",
									"product_id": "openSUSE Leap 15.3",
									"product_identification_helper": {
										"cpe": "cpe:/o:opensuse:leap:15.3"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python2-py-1.8.1-5.6.1.noarch as component of openSUSE Leap 15.3",
					"product_id": "openSUSE Leap 15.3:python2-py-1.8.1-5.6.1.noarch"
				},
				"product_reference": "python2-py-1.8.1-5.6.1.noarch",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			},
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python3-py-1.8.1-5.6.1.noarch as component of openSUSE Leap 15.3",
					"product_id": "openSUSE Leap 15.3:python3-py-1.8.1-5.6.1.noarch"
				},
				"product_reference": "python3-py-1.8.1-5.6.1.noarch",
				"relates_to_product_reference": "openSUSE Leap 15.3"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2020-29651",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2020-29651"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "A denial of service via regular expression in the py.path.svnwc component of py (aka python-py) through 1.9.0 could be used by attackers to cause a compute-time denial of service attack by supplying malicious input to the blame functionality.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"openSUSE Leap 15.3:python2-py-1.8.1-5.6.1.noarch",
					"openSUSE Leap 15.3:python3-py-1.8.1-5.6.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2020-29651",
					"url": "https://www.suse.com/security/cve/CVE-2020-29651"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1179805 for CVE-2020-29651",
					"url": "https://bugzilla.suse.com/1179805"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"openSUSE Leap 15.3:python2-py-1.8.1-5.6.1.noarch",
						"openSUSE Leap 15.3:python3-py-1.8.1-5.6.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 5.5,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:N/I:N/A:H",
						"version": "3.1"
					},
					"products": [
						"openSUSE Leap 15.3:python2-py-1.8.1-5.6.1.noarch",
						"openSUSE Leap 15.3:python3-py-1.8.1-5.6.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2021-07-11T09:21:16Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2020-29651"
		}
	]
}
