{
	"document": {
		"aggregate_severity": {
			"namespace": "https://www.suse.com/support/security/rating/",
			"text": "moderate"
		},
		"category": "csaf_security_advisory",
		"csaf_version": "2.0",
		"distribution": {
			"text": "Copyright 2024 SUSE LLC. All rights reserved.",
			"tlp": {
				"label": "WHITE",
				"url": "https://www.first.org/tlp/"
			}
		},
		"lang": "en",
		"notes": [
			{
				"category": "summary",
				"text": "Security update for python-Django",
				"title": "Title of the patch"
			},
			{
				"category": "description",
				"text": "This update for python-Django fixes the following issues:\n  Update to version 1.11.10 LTS\n  * Fixes CVE-2018-6188 boo#1077714, CVE-2017-7234, CVE-2017-7233,\n    CVE-2017-12794\n",
				"title": "Description of the patch"
			},
			{
				"category": "details",
				"text": "openSUSE-2018-236",
				"title": "Patchnames"
			},
			{
				"category": "legal_disclaimer",
				"text": "CSAF 2.0 data is provided by SUSE under the Creative Commons License 4.0 with Attribution (CC-BY-4.0).",
				"title": "Terms of use"
			}
		],
		"publisher": {
			"category": "vendor",
			"contact_details": "https://www.suse.com/support/security/contact/",
			"name": "SUSE Product Security Team",
			"namespace": "https://www.suse.com/"
		},
		"references": [
			{
				"category": "external",
				"summary": "SUSE ratings",
				"url": "https://www.suse.com/support/security/rating/"
			},
			{
				"category": "self",
				"summary": "URL of this CSAF notice",
				"url": "https://ftp.suse.com/pub/projects/security/csaf/opensuse-su-2018_0632-1.json"
			},
			{
				"category": "self",
				"summary": "SUSE Bug 1077714",
				"url": "https://bugzilla.suse.com/1077714"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2017-12794 page",
				"url": "https://www.suse.com/security/cve/CVE-2017-12794/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2017-7233 page",
				"url": "https://www.suse.com/security/cve/CVE-2017-7233/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2017-7234 page",
				"url": "https://www.suse.com/security/cve/CVE-2017-7234/"
			},
			{
				"category": "self",
				"summary": "SUSE CVE CVE-2018-6188 page",
				"url": "https://www.suse.com/security/cve/CVE-2018-6188/"
			}
		],
		"title": "Security update for python-Django",
		"tracking": {
			"current_release_date": "2018-03-07T13:14:36Z",
			"generator": {
				"date": "2018-03-07T13:14:36Z",
				"engine": {
					"name": "cve-database.git:bin/generate-csaf.pl",
					"version": "1"
				}
			},
			"id": "openSUSE-SU-2018:0632-1",
			"initial_release_date": "2018-03-07T13:14:36Z",
			"revision_history": [
				{
					"date": "2018-03-07T13:14:36Z",
					"number": "1",
					"summary": "Current version"
				}
			],
			"status": "final",
			"version": "1"
		}
	},
	"product_tree": {
		"branches": [
			{
				"branches": [
					{
						"branches": [
							{
								"category": "product_version",
								"name": "python-Django-1.11.10-5.1.noarch",
								"product": {
									"name": "python-Django-1.11.10-5.1.noarch",
									"product_id": "python-Django-1.11.10-5.1.noarch"
								}
							}
						],
						"category": "architecture",
						"name": "noarch"
					},
					{
						"branches": [
							{
								"category": "product_name",
								"name": "SUSE Package Hub 12",
								"product": {
									"name": "SUSE Package Hub 12",
									"product_id": "SUSE Package Hub 12",
									"product_identification_helper": {
										"cpe": "cpe:/o:suse:packagehub:12"
									}
								}
							}
						],
						"category": "product_family",
						"name": "SUSE Linux Enterprise"
					}
				],
				"category": "vendor",
				"name": "SUSE"
			}
		],
		"relationships": [
			{
				"category": "default_component_of",
				"full_product_name": {
					"name": "python-Django-1.11.10-5.1.noarch as component of SUSE Package Hub 12",
					"product_id": "SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
				},
				"product_reference": "python-Django-1.11.10-5.1.noarch",
				"relates_to_product_reference": "SUSE Package Hub 12"
			}
		]
	},
	"vulnerabilities": [
		{
			"cve": "CVE-2017-12794",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2017-12794"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "In Django 1.10.x before 1.10.8 and 1.11.x before 1.11.5, HTML autoescaping was disabled in a portion of the template for the technical 500 debug page. Given the right circumstances, this allowed a cross-site scripting attack. This vulnerability shouldn't affect most production sites since you shouldn't run with \"DEBUG = True\" (which makes this page accessible) in your production settings.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2017-12794",
					"url": "https://www.suse.com/security/cve/CVE-2017-12794"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1056284 for CVE-2017-12794",
					"url": "https://bugzilla.suse.com/1056284"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2018-03-07T13:14:36Z",
					"details": "moderate"
				}
			],
			"title": "CVE-2017-12794"
		},
		{
			"cve": "CVE-2017-7233",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2017-7233"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "Django 1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18 relies on user input in some cases to redirect the user to an \"on success\" URL. The security check for these redirects (namely ``django.utils.http.is_safe_url()``) considered some numeric URLs \"safe\" when they shouldn't be, aka an open redirect vulnerability. Also, if a developer relies on ``is_safe_url()`` to provide safe redirect targets and puts such a URL into a link, they could suffer from an XSS attack.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2017-7233",
					"url": "https://www.suse.com/security/cve/CVE-2017-7233"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1031450 for CVE-2017-7233",
					"url": "https://bugzilla.suse.com/1031450"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2018-03-07T13:14:36Z",
					"details": "low"
				}
			],
			"title": "CVE-2017-7233"
		},
		{
			"cve": "CVE-2017-7234",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2017-7234"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "A maliciously crafted URL to a Django (1.10 before 1.10.7, 1.9 before 1.9.13, and 1.8 before 1.8.18) site using the ``django.views.static.serve()`` view could redirect to any other domain, aka an open redirect vulnerability.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2017-7234",
					"url": "https://www.suse.com/security/cve/CVE-2017-7234"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1031451 for CVE-2017-7234",
					"url": "https://bugzilla.suse.com/1031451"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 6.1,
						"baseSeverity": "MEDIUM",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:C/C:L/I:L/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2018-03-07T13:14:36Z",
					"details": "low"
				}
			],
			"title": "CVE-2017-7234"
		},
		{
			"cve": "CVE-2018-6188",
			"ids": [
				{
					"system_name": "SUSE CVE Page",
					"text": "https://www.suse.com/security/cve/CVE-2018-6188"
				}
			],
			"notes": [
				{
					"category": "general",
					"text": "django.contrib.auth.forms.AuthenticationForm in Django 2.0 before 2.0.2, and 1.11.8 and 1.11.9, allows remote attackers to obtain potentially sensitive information by leveraging data exposure from the confirm_login_allowed() method, as demonstrated by discovering whether a user account is inactive.",
					"title": "CVE description"
				}
			],
			"product_status": {
				"recommended": [
					"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
				]
			},
			"references": [
				{
					"category": "external",
					"summary": "CVE-2018-6188",
					"url": "https://www.suse.com/security/cve/CVE-2018-6188"
				},
				{
					"category": "external",
					"summary": "SUSE Bug 1077714 for CVE-2018-6188",
					"url": "https://bugzilla.suse.com/1077714"
				}
			],
			"remediations": [
				{
					"category": "vendor_fix",
					"details": "To install this SUSE Security Update use the SUSE recommended installation methods like YaST online_update or \"zypper patch\".\n",
					"product_ids": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"scores": [
				{
					"cvss_v3": {
						"baseScore": 7.5,
						"baseSeverity": "HIGH",
						"vectorString": "CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N",
						"version": "3.0"
					},
					"products": [
						"SUSE Package Hub 12:python-Django-1.11.10-5.1.noarch"
					]
				}
			],
			"threats": [
				{
					"category": "impact",
					"date": "2018-03-07T13:14:36Z",
					"details": "important"
				}
			],
			"title": "CVE-2018-6188"
		}
	]
}
